# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0e6bb8a1-6546-4f60-966f-b928b78ffdfc";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-0e6bb8a1-6546-4f60-966f-b928b78ffdfc".device = "/dev/disk/by-uuid/0e6bb8a1-6546-4f60-966f-b928b78ffdfc";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-0e6bb8a1-6546-4f60-966f-b928b78ffdfc";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-0e6bb8a1-6546-4f60-966f-b928b78ffdfc";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DA6C-412D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-41209ad0-8e2e-48fe-a783-160306a71a71"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
